In [1]:
# import dependencies
import getpass
from enum import Enum
import pandas as pd
from datetime import datetime, timedelta
import sqlite3

In [5]:
clientdf = pd.read_csv('MOCK_DATA.csv')
clientdf.head(5)
clientdf = clientdf.reset_index(drop=True)
clientdf.head(5)
clientdf['start_date'] =pd.to_datetime(clientdf['start_date'])
clientdf['end_date'] =pd.to_datetime(clientdf['end_date'],format = '%m/%d/%Y')
clientdf.head(5)

   id first_name   last_name start_date   end_date
0   1     Colman  Strickland 2020-03-16 2020-03-24
1   2     Karrah     Castard 2020-03-20 2020-03-21
2   3    Brannon    Dewhirst 2020-03-13 2020-03-15
3   4     Dionne     Morland 2020-03-23 2020-03-27
4   5  Madelaine      Spinas 2020-03-11 2020-03-13

In [25]:
# testing on datetime
date = '03/20/2020'
date = datetime.strptime(date,'%m/%d/%Y')
id = 3
info = clientdf.loc[clientdf['id']==id]
print(info['start_date'])
# date
if date>= info['start_date'][id-1] and date <= info['end_date'][id-1]:
    print('yes')
else:
    print('no')

2   2020-03-13
Name: start_date, dtype: datetime64[ns]
no

In [118]:
# clientDict = clientdf.to_dict('split')
# clientDict = clientdf.to_dict()
# clientID = list(clientDict['id'].values())
# clientID

In [6]:
servicedf = pd.read_csv('service.csv')
servicedf.head()
# datetime.strptime(servicedf['start_time'],'%I:%M %a')

,id,first_name,last_name,service,date,start_time,end_time,duration,total_price,confirmation
0,1,Colman,Strickland,facial,3/17/2020,8:00 AM,8:30 AM,30,60,100facial

In [12]:
pricedf = pd.read_csv('price.csv')
pricedf.head()

               service  unit_price
0         mineral bath         2.5
1              massage         3.0
2               facial         2.0
3  Specialty treatment         3.5

In [3]:
# testing on time

# time = input('time')
# # timeF = datetime.strptime(time,'%I:%M %p').time()
# servicedf['start_time']
# if str(time) in str(servicedf['start_time']):
#     print('yes')
# else:
#     print('no')
#     print(time)
#     print(servicedf['start_time'][0])
# timeF
time = '8:00 am'
# time.split(':')

timeF = datetime.strptime(time,'%I:%M %p')
du = '30'
# duF = datetime.strptime(du,'%M').time()
duF = timedelta(minutes=int(du))

# ((duF+timeF).time()).strftime('%I:%M %p')
duF

datetime.timedelta(seconds=1800)

In [7]:
class MenuOption(Enum):
    """
    assign number to different layers of menu, easier for later modification.
    """
    mainMenu = 1
    facial = 2
    massage = 3
    miner = 4
    specilty = 5
    lookUp = 6
    maintenance = 7
    signOut = 8

In [8]:
class Mainmenu(object):
    def __init__(self):
        self.main_menu = {
            1: 'Facial Scheduling',
            2: 'Massage Scheduling',
            3: 'Mineral Bath Scheduling',
            4: 'Specialty Treatment Scheduling',
            5: 'Look Up or Edit an Appointment',
            6: 'Perform Maintenance',
            7: 'Sign Out or Quit'
        }
        self.facial = {
            1: '30',
            2: '60'
        }  
    def printOption(self,option=MenuOption.mainMenu.value):
        if option == MenuOption.mainMenu.value:
            print("Main Menu")
            print()
            for i in self.main_menu:
                print(i,self.main_menu[i])
            print()
        elif option == MenuOption.facial.value:
            print("Facial Scheduling: ")
            print()
            for i in self.facial:
                print(i,self.facial[i])
            print()

In [9]:
class Login(object):
    def __init__(self):
        self.password = None
        self.userChoice = None
    def logIn(self):
        # username = input('Username: ')
        # getpass library hides the password
        print('Please type your password below then press ENTER or RETURN.')
        self.password = getpass.getpass('Password: ') 
        if self.password == 'admin':
            main = Mainmenu()
            main.printOption()
            self.userChoice = input("Type the number of the option you want, then press ENTER or RETURN.")
            response = True
            while response:
                if self.userChoice=='1':  
                    main.printOption(2)   # printout facial menu, 2 is number in MenuOption
                    facial = Reservation()
                    _min = input("Type the number of the option you want, then press ENTER or RETURN.")
                    facial.facial('facial',_min)
                    response = False
                elif self.userChoice=='7':
                    print("You are signing out the program")
                    self.logIn()
                    response = False
                else:
                    print( "Sorry, that is not a recognized command. Please type the number for one of the above options and press ENTER or RETURN.")
                    main.printOption()
                    self.userChoice = input("Type the number of the option you want, then press ENTER or RETURN.")
                    response = True

        else:
            print("Sorry, but that password is not recognized. Please try again.")
            self.logIn()

In [44]:
class ServiceTime(Enum):
    """
    assign number to different layers of menu, easier for later modification.
    """
    _30min = 30
    _60min = 60
    _90min = 90

In [102]:
date = datetime.strptime('03/20/2020','%m/%d/%Y')
# date = '03/20/2020'
servicedf['date']
servicedf.loc[servicedf['date']==date]

Empty DataFrame
Columns: [id, first_name, last_name, service, date, start_time, end_time, duration, confirmation]
Index: []

In [31]:
class Reservation(object):
    def __init__(self):
        pass
    def facial(self,service,option):
        unitPrice = pricedf.loc[pricedf['service']==service]
        unitPrice = int(unitPrice['unit_price'])
        facial = Mainmenu()
        self.client = int(input("What is your client ID?"))
        if self.client in clientdf['id']:
            info = clientdf.loc[clientdf['id']==self.client]
            
#             print(info['start_date'])
          
#             print(self.date)
            self.response = True
            while self.response:
                self.date = input("What date?")
                self.date = datetime.strptime(self.date,'%m/%d/%Y').date()
                if self.date>= info['start_date'][self.client-1] and self.date <= info['end_date'][self.client-1]:
                    self.response = False
                    self.r = True
                    while self.r:
                        self.startTime = input("What is the start time?")
    #                     self.startTime = datetime.strptime(self.startTime,'%I:%M %p').time()
                        timeDf = servicedf.loc[servicedf['date']==self.date]
                        if self.startTime in str(timeDf['start_time']):
                            print('sorry this time is not available, please choose another time')
                            self.r = True
                        else:
                            startTimeF = datetime.strptime(self.startTime,'%I:%M %p')
#                             print(option)
#                             查这个self.facial[option]是否出来30，这里有问题现在
                            duration = facial.facial[int(option)]
#                             print(duration)
                            duF = timedelta(minutes=int(duration))
                            self.endTime = ((duF+startTimeF).time()).strftime('%I:%M %p')
#                             print(info['first_name'][1])
#                             print(info['last_name'][1])
                            totalPrice = int(duration)*unitPrice
                            print(f'The total price is {totalPrice}')
                            confInput = input('Would you like to confirm your appointment? (Y/N)')
                            if confInput == 'Y':
                                print(f'Your confirmation code is {str(101)+service}.')
                                self.servicedf = servicedf.append({
                                    'id':self.client,
                                    'first_name': info['first_name'][1],
                                    'last_name': info['last_name'][1],
                                    'date': self.date,
                                    'start_time': self.startTime,
                                    'end_time': self.endTime,
                                    'duration': duration,
                                    'service': service,
                                    'total_price': totalPrice,
                                    'confirmation': str(101)+service
                                    }, ignore_index=True)
                                display(self.servicedf.head())
                                self.r = False
                            else:
                                print('no appointment is made')
                                self.r = False
                            
                else:
                    print('wrong date')
                    self.response = True
                                                       
        else:
            print('not in the db')

In [50]:
# class ClientInfo(object):
#     def __init__(self):
#         pass
#     def client(self,option):
#         client = input("What is your client ID?")
#         if client in clientdf['id']:
#             response = True
#             while response:
#                 startTime = input("What is the start time?")
#                 if startTime in servicedf['start_time']:
#                     print('sorry this time is not available, please choose another time')
#                     response = True
#                 else:
#                     servicedf['id'] = client
#                     servicedf['start_time'] = startTime
#                     servicedf['end_time']= date
#                     servicedf['duration']=option

In [32]:
login = Login()
login.logIn()

Please type your password below then press ENTER or RETURN.
Password: ········
Main Menu

1 Facial Scheduling
2 Massage Scheduling
3 Mineral Bath Scheduling
4 Specialty Treatment Scheduling
5 Look Up or Edit an Appointment
6 Perform Maintenance
7 Sign Out or Quit

Type the number of the option you want, then press ENTER or RETURN.1
Facial Scheduling:

1 30
2 60

Type the number of the option you want, then press ENTER or RETURN.2
What is your client ID?2
What date?03/20/2020
What is the start time?8:00 am
The total price is 120
Would you like to confirm your appointment? (Y/N)Y
Your confirmation code is 101facial.

,id,first_name,last_name,service,date,start_time,end_time,duration,total_price,confirmation
0,1,Colman,Strickland,facial,3/17/2020,8:00 AM,8:30 AM,30,60,100facial
1,2,Karrah,Castard,facial,2020-03-20,8:00 am,09:00 AM,60,120,101facial

In [67]:
servicedf.head()

,id,first_name,last_name,service,date,start_time,end_time,duration,confirmation
0,1,Colman,Strickland,facial,3/17/2020,8:00 am,8:30 am,30,13178facial